# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]

# Custom hooks for repository and BDD validation
-   repo: local
    hooks:
    -   id: repo-health-check
        name: Repository Health Check
        entry: python tools/repo_health_check.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]

    -   id: bdd-validator
        name: BDD Validator
        entry: python tools/bdd_validator.py
        language: system
        files: ^(tests/bdd/.*\.feature|tests/bdd/steps/.*\.py)$
        pass_filenames: false
        stages: [commit]

    -   id: bdd-coverage
        name: BDD Coverage Check
        entry: python tools/bdd_coverage_report.py
        language: system
        files: ^(tests/bdd/.*\.feature|tests/bdd/steps/.*\.py)$
        pass_filenames: false
        stages: [push]

    -   id: bdd-duplication
        name: BDD Duplication Check
        entry: python tools/bdd_duplication_analyzer.py --threshold 0.7
        language: system
        files: ^tests/bdd/.*\.feature$
        pass_filenames: false
        stages: [push]

    -   id: bdd-docs
        name: BDD Documentation Generator
        entry: python tools/bdd_docs_generator.py
        language: python
        files: ^(tests/bdd/.*\.feature|tests/bdd/steps/.*\.py)$
        pass_filenames: false
        stages: [commit]

    -   id: bdd-tests
        name: BDD Tests
        entry: python tools/bdd_test_runner.py
        language: python
        files: ^(tests/bdd/.*\.feature|tests/bdd/steps/.*\.py)$
        pass_filenames: false
        stages: [push]
        args: ["--no-parallel"]  # Run sequentially in pre-commit

    -   id: bdd-performance
        name: BDD Performance Check
        entry: python tools/bdd_test_runner.py
        language: python
        files: ^(tests/bdd/.*\.feature|tests/bdd/steps/.*\.py)$
        pass_filenames: false
        stages: [push]
        args: ["--tags", "performance"]  # Only run performance-tagged tests
