site_name: Portal Explorer Documentation
site_description: Documentation for the Portal Explorer tool
site_author: Liminal Commons
repo_url: https://github.com/liminalcommons/gather-utils
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - User Guide: user_guide/index.md
  - API Reference: api/index.md
  - CLI Reference: cli/index.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/liminalcommons/gather-utils
  version:
    provider: mike
